language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install autodocsumm sphinx_rtd_theme jieba

script:
  - PYTHONHASHSEED=32 TZ=Asia/Shanghai pytest
  - python setup.py sdist
  - python setup.py bdist_wheel -p any
  - rm -rf build
  - python setup.py bdist_wheel -p manylinux1_x86_64
  - rm -rf build
  - python setup.py bdist_wheel -p win32
  - rm -rf build
  - python setup.py bdist_wheel -p win_amd64
  - rm -rf build
  - sphinx-build doc build/doc

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
  - provider: s3
    access_key_id: $AWS_KEY_ID
    secret_access_key: $AWS_ACCESS_KEY
    bucket: shinnydeploy
    region: ap-east-1
    local_dir: build/doc
    upload-dir: "docs/tqsdk-python/$TRAVIS_BRANCH"
    skip_cleanup: true
    on:
      all_branches: true
  - provider: s3
    access_key_id: $AWS_KEY_ID
    secret_access_key: $AWS_ACCESS_KEY
    bucket: shinnydeploy
    region: ap-east-1
    local_dir: dist
    upload-dir: "dist/tqsdk-python/$TRAVIS_BRANCH"
    skip_cleanup: true
    on:
      all_branches: true
  - provider: pypi
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    skip_cleanup: true
    skip_existing: true
    on:
      tags: true
